media:
  input: public/images
  output: /images

content:
  - name: blog
    label: Blog Posts
    type: collection
    path: src/content/blog
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: pubDate
        label: Publish Date
        type: date
        required: true
      - name: description
        label: Description
        type: string
      - name: body
        label: Body
        type: rich-text