media:
  input: public/images
  output: /images

content:
  - name: blog
    label: Blog Posts
    type: collection
    path: src/content/blog
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: pubDate
        label: Publish Date
        type: date
        required: true
      - name: description
        label: Description
        type: string
      - name: author
        label: Author
        type: string
        default: "Darwin Sayo"
      - name: categories
        label: Categories
        type: string
      - name: tags
        label: Tags
        type: string
      - name: image
        label: Featured Image
        type: image
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: body
        label: Body
        type: rich-text